unexpected handler called
caught bad_exception